"""
Copyright (c) 2021-, Haibin Wen, sunnypilot, and a number of other contributors.

This file is part of sunnypilot and is licensed under the MIT License.
See the LICENSE.md file in the root directory for more details.
"""
from openpilot.sunnypilot.custom.longitudinal.curve_evidence.map_controller import (
  SmartCruiseControlMap,
  MapState,
  VisionState,
  ACTIVE_STATES,
  ENABLED_STATES,
  velocities_from_param,
  _is_finite_number,
  _valid_velocity_entry,
  _dedupe_route_points,
  calculate_accel,
  calculate_velocity,
  calculate_distance,
  distance_to_point,
  R,
  TO_RADIANS,
  TO_DEGREES,
  TARGET_JERK,
  TARGET_ACCEL,
  TARGET_OFFSET,
  MAX_ROUTE_TARGET_DISTANCE,
  MAX_SHORT_DROP_DISTANCE,
  MAX_SHORT_DROP_DELTA_V,
  SHORT_DROP_CONFIRM_POINTS,
  MATERIAL_DROP_DELTA_V,
  MIN_CURRENT_LAT_ACCEL_CORROBORATION,
  MIN_MODEL_PRED_LAT_ACCEL_CORROBORATION,
  _ROUTE_POINT_EPS,
)

__all__ = [
  "SmartCruiseControlMap",
  "MapState",
  "VisionState",
  "ACTIVE_STATES",
  "ENABLED_STATES",
  "velocities_from_param",
  "_is_finite_number",
  "_valid_velocity_entry",
  "_dedupe_route_points",
  "calculate_accel",
  "calculate_velocity",
  "calculate_distance",
  "distance_to_point",
  "R",
  "TO_RADIANS",
  "TO_DEGREES",
  "TARGET_JERK",
  "TARGET_ACCEL",
  "TARGET_OFFSET",
  "MAX_ROUTE_TARGET_DISTANCE",
  "MAX_SHORT_DROP_DISTANCE",
  "MAX_SHORT_DROP_DELTA_V",
  "SHORT_DROP_CONFIRM_POINTS",
  "MATERIAL_DROP_DELTA_V",
  "MIN_CURRENT_LAT_ACCEL_CORROBORATION",
  "MIN_MODEL_PRED_LAT_ACCEL_CORROBORATION",
  "_ROUTE_POINT_EPS",
]
